<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit007b39bd5fcc97bdf7b6c5f3ab5245a2
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.Class.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit007b39bd5fcc97bdf7b6c5f3ab5245a2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit007b39bd5fcc97bdf7b6c5f3ab5245a2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit007b39bd5fcc97bdf7b6c5f3ab5245a2::$classMap;

        }, null, ClassLoader::class);
    }
}
